import { Kanit } from "next/font/google";
import "./globals.css";
// import { Providers } from "./store/provider";
// import MenuTabOpd from "@/app/components/aia/Opd/MenuTabOpd";
// import Navbar from "./components/Navbar";
const kanit = Kanit({
  subsets: ["latin"],
  weight: ["100", "300", "700"],
  variable: "--font-kanit",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={kanit.variable}>
        {/* <Navbar /> */}
        {/* <Providers> */}
          {/* <MenuTabOpd /> */}
          <div className="kanit">{children}</div>
        {/* </Providers> */}
      </body>
    </html>
  );
}
